### ISSUE TITLE
Insulation score calculation with more than 3 HiC matrices

### ISSUE THREAD

**Issue by meisterpeter** [robinweide/GENOVA#246] opened 2021-01-28 17:25 UTC
Hi Robin,

When I try to calculate insulation scores with more than 3 matrices, the `insulation_score` command outputs the warning 
`Warning message:
In merge.data.table(insula, raw[[i]], all = TRUE, by = "grp") :
  column names 'V2.x', 'V2.y' are duplicated in the result`
The resulting insulation score cannot be visualised, `visualise(insulation_score)` returns `Error in `[.data.frame`(df, , expnames) : undefined columns selected`
Works like a charm with 3 matrices.
Not clear whether this is an intended limitation (only 3 matrices) or a bug. Cheers,

Peter

**Comment by robinweide** [comment] 2021-01-28 17:45
Hi Peter,

It would be helpful to share the command you used.
Could it be that your explist contains two (or more) contacts-objects with the same sample name?

Best,
Robin

**Comment by meisterpeter** [comment] 2021-01-28 18:41
#Contact matrices loading
N2_25kb_cooler <- load_contacts(signal_path = "./cool_files_MD/N2.mcool",
                                  sample_name = "N2",
                                  balancing = T,
                                  resolution = 25000,
                                  colour = "black")
S366_25kb_cooler <- load_contacts(signal_path = "./cool_files_MD/366b2.mcool",
                                  sample_name = "TEV_control",
                                  balancing = T,
                                  resolution = 25000,
                                  colour = "grey")
S382_25kb_cooler <- load_contacts(signal_path = "./cool_files_MD/382b1.mcool",
                                  sample_name = "Cond_I_IDC",
                                  balancing = T,
                                  resolution = 25000,
                                  colour = "blue")
S775_25kb_cooler <- load_contacts(signal_path = "./cool_files_MD/775b1.mcool",
                                  sample_name = "Cond_II",
                                  balancing = T,
                                  resolution = 25000,
                                  colour = "green")
S784_25kb_cooler <- load_contacts(signal_path = "./cool_files_MD/784b1.mcool",
                                  sample_name = "Cohesin_scc-1",
                                  balancing = T,
                                  resolution = 25000,
                                  colour = "red")
All_strains_25kb_insulation <-   insulation_score(list(N2_25kb_cooler,
                        S366_25kb_cooler,
                        S382_25kb_cooler,
                        S775_25kb_cooler,
                        S784_25kb_cooler
                      ),
                   window = 25)

**Comment by teunbrand** [comment] 2021-01-28 19:34
Thank you Peter, I could reproduce the issue using the following code:

``` r
library(GENOVA)

exp1 <- get_test_data("150k")
exp2 <- exp1
exp3 <- exp1
exp4 <- exp1
expnames(exp1) <- "test1"
expnames(exp2) <- "test2"
expnames(exp3) <- "test3"
expnames(exp4) <- "test4"

ins <- insulation_score(
  list(exp1, exp2, exp3, exp4),
  window = 25
)
```

It appeared to be a simple issue related to column names during the collection of the results and required a small fix.

**Comment by meisterpeter** [comment] 2021-01-28 21:00
Hi Teun, 
Thanks for the fix, the calculation now works, but visualise still crashes with 
`Error in `[.data.frame`(df, , expnames) : undefined columns selected`

**Comment by teunbrand** [comment] 2021-02-01 15:52
Hello Peter,

My attempt to reproduce this error is running the code above and afterwards running the following.
```
visualise(ins, chr = "chr22")
```
I get no error running this and a plot comes out. Do you get an error with the code I posted and the line above?
If not, I would need some more details to debug this issue.

Best wishes,
Teun

**Comment by meisterpeter** [comment] 2021-02-02 14:24
Hi Teun,

I updated to the lastest dev version of GENOVA and I get the same error:

Here is the command (the same matrices work perfectly to make insulograms):

All_strains_25kb_insulation <-   insulation_score(
+                   list(N2_25kb_cooler,
+                         S366_25kb_cooler,
+                         S382_25kb_cooler,
+                         S775_25kb_cooler,
+                         S784_25kb_cooler
+                       ),
+                    window = 25)
> visualise(All_strains_25kb_insulation,
+           chr = 'chrX', start = 1, end=17e6,
+           contrast = 1)
Error in `[.data.frame`(df, , expnames) : undefined columns selected

The error comes from one of the sample names (scc-1), which had a “-“ in it (sorry, worm gene names are simply like that…).
I changed it and now it works! Maybe something to write in the manual (which characters are forbidden in sample names 😉

[cid:image001.png@01D6F977.85292920]
Thanks for looking into this!

Best,

Peter

**Comment by teunbrand** [comment] 2021-02-02 17:02
Hi Peter,

Thank you, that give me an important clue for debugging the issue.
It seems the issue is caused by `data.frame()`'s automatic 'fixing' of column names (see `?make.names`).
I can fix this on the insulation score visualisation side, but maybe we should consider forcing names to be syntactically valid in general, by adjusting this in `load_contacts()` and the `expnames<-` functions.
@robinweide, do you have opinions on forcing valid names?

Best,
Teun

**Comment by robinweide** [comment] 2021-02-02 17:54
Nomenclature is full of wonderfully weird characters: I'm all for allowing them (including deltas). 

I guess the characters are only a problem when used as column names? If that's the case, bypass `make.names`.
If it is also an issue as a value in a df/dt, we should put a warning in `load_contacts` that sample_names are converted to "R-compliant names".

**Comment by teunbrand** [comment] 2021-02-02 18:24
Yes, just as column names of `data.frame`s, `data.table` has no problems so most of the code should be fine. It's just the rare occurrence that we program with sample names in `data.frame`s in wide-format that could give errors. I'm fine with fixing any more bugs of the same sort as we encounter them, we don't have to restrict the names of contacts objects.

Here is an example that might cause an inconvenience:
``` r
sample_name <- "test-1"
df <- as.data.frame(setNames(list(1), sample_name))
print(df) # converted dash to dot
#>   test.1
#> 1      1
df[[sample_name]]
#> NULL

# Compare to:
sample_name <- "test1"
df <- as.data.frame(setNames(list(1), sample_name))
df[[sample_name]]
#> [1] 1
```

**Comment by teunbrand** [comment] 2021-02-03 08:19
Alright I think this might be fixed now. Thanks everyone involved!

**Closed by teunbrand** 2021-02-03 08:19 UTC
