### ISSUE TITLE
APA fails on unsorted anchor list (?)

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#204] opened 2020-05-20 16:25 UTC
APA function seems to fail when an unsorted loop anchor list is used. At least ‘Error: No suitable anchors left after out-of-bounds filtering.’ can be solved by sorting loop anchor list.

**Comment by teunbrand** [comment] 2020-05-21 06:44
I'm not sure what you mean with loop anchor list? Is it a list of BEDPE-formatted data.frames, a list of pre-converted anchor objects or simply an unlisted/flat BEDPE-formatted data.frame?

**Comment by deWitLab** [comment] 2020-05-21 07:51
Unlisted BEDPE formatted data.frame (6 columns).

**Comment by teunbrand** [comment] 2020-05-25 14:40
I can't reproduce this error, I tried the following:

```
scrambled <- bedpe[sample(nrow(bedpe)),]
dim(bedpe)
# [1] 6976    6

# Run APAs
apa_standard <- APA(list(exp, exp2), bedpe = bedpe)
apa_scrambled <- APA(list(exp, exp2), bedpe = scrambled)

# Extract raw data
standard <- apa_standard$signal_raw[[1]]
scrambld <- apa_scrambled$signal_raw[[1]]

# Order identically
standard <- standard[order(rownames(standard)),,]
scrambld <- scrambld[order(rownames(scrambld)),,]

# Check equivalence
identical(standard, scrambld)
# [1] TRUE
```

**Comment by teunbrand** [comment] 2020-05-26 14:11
I'm closing this for now, if it is more clear how to make this error occur, please feel free to reopen.

**Closed by teunbrand** 2020-05-26 14:11 UTC
